#
# NodeMCU Test Firmware
#
# (c) 2022 Fabien Pollet <polletfa@posteo.de>
# MIT License (see LICENSE.md file)
#

firmware:
	@echo Use the Arduino IDE to compile firmware.ino

doc:
	doxygen doxygen.conf

clean:
	rm -fr _gen _doc
